<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "smartmap"
 *
 * Auto generated by Extension Builder 2015-07-18
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
    'title'        => 'Smart Map',
    'description'  => 'A really smart TYPO3 CMS Map Extension for pretty interaction.',
    'category'     => 'plugin',
    'author'       => 'Sebastian Gierth, Steve Lenz',
    'author_email' => 'seb91gi@yahoo.de, kontakt@steve-lenz.de',
    'state'        => 'alpha',
    'internal'     => '',
    'uploadfolder' => '0',
    'createDirs'   => '',
    'clearCacheOnLoad' => 0,
    'version'      => '0.4.2',
    'constraints'  => array(
        'depends'   => array(
            'typo3' => '6.2.14-7.3.99',
        ),
        'conflicts' => array(),
        'suggests'  => array(
            'phpunit' => '4.4.0',
        ),
    ),
);
